/**
 * Canonical Block Document v1.
 *
 * A CMS-neutral, versioned document model that sits between import/export
 * adapters (WordPress, Shopify, Wix, ...) and our editor/persistence format.
 * Stage 1 is deliberately additive: nothing here is persisted yet and
 * `seo_content.content_json` stays a Tiptap document.
 *
 * Two ideas make this model useful rather than a lowest-common-denominator
 * format:
 *   1. a semantic projection (`type` + semantic `attrs` + inline `content` +
 *      nested `children`) that AI/analytics can reason about, and
 *   2. an optional lossless `source` envelope (original CMS, block/node type,
 *      raw attrs, WP `innerContent`) so an adapter can emit a document back to
 *      its origin without dropping CMS-specific detail.
 *
 * Unknown block/mark types are allowed on purpose: adapters must be able to
 * carry content they do not yet understand (as `custom`) instead of dropping
 * it. Structural validation is still strict.
 */

// ---------------------------------------------------------------------------
// Vocabulary
// ---------------------------------------------------------------------------

export const CANONICAL_DOCUMENT_VERSION = 1 as const;

/**
 * Semantic block types known to v1. This is documentation + adapter hints, not
 * a closed set: a document may carry any non-empty, well-formed block type, and
 * unknown ones should use `custom` with a `source`. `canonicalBlockTypeOf`
 * reports whether a type is part of the known vocabulary.
 */
export const CANONICAL_BLOCK_TYPES = [
  'paragraph',
  'heading',
  'list',
  'listItem',
  'quote',
  'code',
  'image',
  'divider',
  'table',
  'tableRow',
  'tableCell',
  'group',
  'columns',
  'column',
  'embed',
  'html',
  'custom',
] as const;

export type KnownCanonicalBlockType = (typeof CANONICAL_BLOCK_TYPES)[number];

/** Mark types v1 knows how to render. Unknown marks are still structurally
 *  valid so a conversion never silently drops formatting it cannot name. */
export const CANONICAL_MARK_TYPES = [
  'bold',
  'italic',
  'strike',
  'code',
  'underline',
  'sub',
  'sup',
  'link',
] as const;

export type KnownCanonicalMarkType = (typeof CANONICAL_MARK_TYPES)[number];

/** Upper bounds keep a hand-edited or hostile document from reaching adapters. */
export const CANONICAL_MAX_BLOCKS = 5000;
const MAX_DEPTH = 200;
const MAX_ID_LENGTH = 128;
const MAX_TYPE_LENGTH = 80;

const KNOWN_BLOCK_TYPES: ReadonlySet<string> = new Set(CANONICAL_BLOCK_TYPES);
const KNOWN_MARK_TYPES: ReadonlySet<string> = new Set(CANONICAL_MARK_TYPES);

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/** CMS identifier for the origin of a block. Open-ended so future adapters can
 *  add values without a contracts release. */
export type CanonicalSourceCms = 'tiptap' | 'wordpress' | 'shopify' | 'wix' | 'html' | (string & {});

/**
 * Lossless origin envelope. Only populated when the information is not already
 * carried by the semantic projection - primarily for `custom`/unsupported
 * content and for adapters that need the original representation to re-emit.
 */
export interface SourceRef {
  cms: CanonicalSourceCms;
  /** Original node type / block name (e.g. TipTap `mention`, WP `core/group`). */
  type?: string;
  /** Original raw attributes, preserved verbatim when present. */
  attrs?: Record<string, unknown>;
  /** The original attribute payload as text, kept when `attrs` cannot hold it
   *  (malformed or non-object JSON). Serializers should prefer this over
   *  re-encoding `attrs` so nothing is lost at the interchange boundary. */
  attrsRaw?: string;
  /** WordPress `innerContent`: static HTML fragments interleaved with `null`
   *  placeholders at child-block positions. Enables byte-exact WP round trips. */
  innerContent?: Array<string | null>;
}

export interface CanonicalMark {
  type: string;
  attrs?: Record<string, unknown>;
}

export interface CanonicalText {
  type: 'text';
  text: string;
  marks?: CanonicalMark[];
}

export interface CanonicalBreak {
  type: 'break';
}

/** Escape hatch for inline content an adapter cannot name yet. `raw` holds the
 *  original JSON so a round trip can restore it exactly. */
export interface CanonicalInlineUnsupported {
  type: 'inlineUnsupported';
  raw?: string;
  source?: SourceRef;
}

export type CanonicalInline = CanonicalText | CanonicalBreak | CanonicalInlineUnsupported;

export interface CanonicalBlock {
  /** Stable, bounded address. Deterministic when generated by an adapter. */
  id?: string;
  /** Semantic type; see CANONICAL_BLOCK_TYPES. Open vocabulary. */
  type: string;
  /** Semantic attributes only (e.g. heading `level`, image `mediaId`). Raw
   *  origin attributes live on `source.attrs`. */
  attrs?: Record<string, unknown>;
  /** Inline content for leaf blocks (paragraph, heading, code, ...). */
  content?: CanonicalInline[];
  /** Nested blocks (containers, list items, rows/cells, ...). */
  children?: CanonicalBlock[];
  /** Lossless origin envelope (see SourceRef). */
  source?: SourceRef;
  /** Raw HTML fallback for `html`/`custom` blocks when no structure is known. */
  rawHtml?: string;
}

export interface CanonicalMeta {
  title?: string;
  language?: string | null;
}

export interface CanonicalDocument {
  version: typeof CANONICAL_DOCUMENT_VERSION;
  blocks: CanonicalBlock[];
  meta?: CanonicalMeta;
}

// ---------------------------------------------------------------------------
// Construction
// ---------------------------------------------------------------------------

/** A brand-new empty canonical document (single empty paragraph), mirroring
 *  `tiptapEmptyDoc()` so round trips of an empty article are stable. */
export function canonicalEmptyDoc(): CanonicalDocument {
  return { version: CANONICAL_DOCUMENT_VERSION, blocks: [{ type: 'paragraph' }] };
}

/** True when `type` is part of the known v1 semantic vocabulary. */
export function canonicalBlockTypeOf(type: string): type is KnownCanonicalBlockType {
  return KNOWN_BLOCK_TYPES.has(type);
}

/** True when `type` is a known v1 mark type. */
export function canonicalMarkTypeOf(type: string): type is KnownCanonicalMarkType {
  return KNOWN_MARK_TYPES.has(type);
}

// ---------------------------------------------------------------------------
// Validation
// ---------------------------------------------------------------------------

const ID_RE = /^[A-Za-z0-9][A-Za-z0-9_-]*$/;
const TYPE_RE = /^[a-z][A-Za-z0-9]*(?:[/_-][A-Za-z0-9]+)*$/;
const CMS_RE = /^[a-z][a-z0-9_-]*$/;

function isPlainObject(value: unknown): value is Record<string, unknown> {
  return !!value && typeof value === 'object' && !Array.isArray(value);
}

function isValidId(value: unknown): boolean {
  return typeof value === 'string' && value.length <= MAX_ID_LENGTH && ID_RE.test(value);
}

function isValidType(value: unknown): boolean {
  return typeof value === 'string' && value.length <= MAX_TYPE_LENGTH && TYPE_RE.test(value);
}

function isValidSourceRef(value: unknown): value is SourceRef {
  if (!isPlainObject(value)) return false;
  const cms = value.cms;
  if (typeof cms !== 'string' || cms.length === 0 || cms.length > 40 || !CMS_RE.test(cms)) return false;
  if (value.type !== undefined && !isValidType(value.type)) return false;
  if (value.attrs !== undefined && !isPlainObject(value.attrs)) return false;
  if (value.attrsRaw !== undefined && typeof value.attrsRaw !== 'string') return false;
  if (value.innerContent !== undefined) {
    if (!Array.isArray(value.innerContent)) return false;
    if (!value.innerContent.every((part) => part === null || typeof part === 'string')) return false;
  }
  return true;
}

function isValidCanonicalMark(value: unknown): value is CanonicalMark {
  if (!isPlainObject(value)) return false;
  if (!isValidType(value.type)) return false;
  if (value.attrs !== undefined && !isPlainObject(value.attrs)) return false;
  if (value.type === 'link') {
    const attrs = value.attrs;
    if (!isPlainObject(attrs)) return false;
    const href = attrs.href;
    if (typeof href !== 'string' || href.trim().length === 0 || href.length > 4096) return false;
    if (attrs.rel !== undefined && typeof attrs.rel !== 'string') return false;
    if (attrs.target !== undefined && typeof attrs.target !== 'string') return false;
  }
  return true;
}

function isValidCanonicalInline(value: unknown): value is CanonicalInline {
  if (!isPlainObject(value)) return false;
  switch (value.type) {
    case 'text':
      if (typeof value.text !== 'string') return false;
      if (value.marks !== undefined) {
        if (!Array.isArray(value.marks) || !value.marks.every(isValidCanonicalMark)) return false;
      }
      return true;
    case 'break':
      return true;
    case 'inlineUnsupported':
      if (value.raw !== undefined && typeof value.raw !== 'string') return false;
      if (value.source !== undefined && !isValidSourceRef(value.source)) return false;
      return true;
    default:
      return false;
  }
}

interface WalkState {
  depth: number;
  blocks: number;
}

function isValidCanonicalBlock(value: unknown, state: WalkState): value is CanonicalBlock {
  if (!isPlainObject(value)) return false;
  if (state.depth > MAX_DEPTH) return false;
  if (++state.blocks > CANONICAL_MAX_BLOCKS) return false;

  if (value.id !== undefined && !isValidId(value.id)) return false;
  if (!isValidType(value.type)) return false;
  if (value.attrs !== undefined && !isPlainObject(value.attrs)) return false;
  if (value.rawHtml !== undefined && typeof value.rawHtml !== 'string') return false;
  if (value.source !== undefined && !isValidSourceRef(value.source)) return false;

  if (value.content !== undefined) {
    if (!Array.isArray(value.content) || !value.content.every(isValidCanonicalInline)) return false;
  }
  if (value.children !== undefined) {
    if (!Array.isArray(value.children)) return false;
    state.depth += 1;
    for (const child of value.children) {
      if (!isValidCanonicalBlock(child, state)) return false;
    }
    state.depth -= 1;
  }

  // Semantic shape checks for the types whose attributes drive rendering.
  if (value.type === 'heading') {
    const level = value.attrs?.level;
    if (typeof level !== 'number' || !Number.isInteger(level) || level < 1 || level > 6) return false;
  }
  if (value.type === 'list') {
    if (typeof value.attrs?.ordered !== 'boolean') return false;
    const start = value.attrs.start;
    if (start !== undefined && (typeof start !== 'number' || !Number.isInteger(start))) return false;
  }
  if (value.type === 'image') {
    const attrs = value.attrs ?? {};
    if (attrs.mediaId !== undefined && typeof attrs.mediaId !== 'string') return false;
    if (attrs.src !== undefined && typeof attrs.src !== 'string') return false;
    if (attrs.alt !== undefined && typeof attrs.alt !== 'string') return false;
    if (attrs.caption !== undefined && typeof attrs.caption !== 'string') return false;
    if (attrs.width !== undefined && typeof attrs.width !== 'number') return false;
    if (attrs.height !== undefined && typeof attrs.height !== 'number') return false;
  }
  return true;
}

/**
 * Recursive, structural validation. Rejects malformed documents before they
 * reach an adapter while still allowing unknown semantic types (the `custom`
 * escape hatch). Does not mutate its input.
 */
export function isValidCanonicalDoc(value: unknown): value is CanonicalDocument {
  if (!isPlainObject(value)) return false;
  if (value.version !== CANONICAL_DOCUMENT_VERSION) return false;
  if (!Array.isArray(value.blocks)) return false;

  if (value.meta !== undefined) {
    if (!isPlainObject(value.meta)) return false;
    if (value.meta.title !== undefined && typeof value.meta.title !== 'string') return false;
    if (value.meta.language !== undefined && value.meta.language !== null && typeof value.meta.language !== 'string') {
      return false;
    }
  }

  const state: WalkState = { depth: 0, blocks: 0 };
  for (const block of value.blocks) {
    if (!isValidCanonicalBlock(block, state)) return false;
  }
  return true;
}
