/**
 * Confirmed AI image generation tests (R4.5B).
 *
 * Pins the spending path: generation only runs once the caller has resolved a
 * policy and confirmation, it is bound to the effective BYOK credential, the
 * generated bytes are persisted as an ordinary library row with non-secret
 * provenance, and every failure is an honest typed error.
 */
import { describe, expect, it, vi } from 'vitest';
import type {
  ImageInsertionContext,
  MediaItemDto,
  MediaProvider,
  MediaResult,
  VisualDesignIntent,
} from '@seo/contracts';
import {
  IMAGE_GENERATION_DEFAULT_MODEL,
  acquireGeneratedImage,
  buildImageGenerationPrompt,
  imageGenerationModel,
} from './imageGenerationAcquisition.js';
import type { ImportExternalMediaInput } from './mediaService.js';

function pngBuffer(w = 1024, h = 1024): Buffer {
  const buf = Buffer.alloc(24);
  Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]).copy(buf, 0);
  buf.writeUInt32BE(13, 8);
  buf.write('IHDR', 12, 'latin1');
  buf.writeUInt32BE(w, 16);
  buf.writeUInt32BE(h, 20);
  return buf;
}

const context: ImageInsertionContext = {
  revision: 'rev1:abcdef0123456789',
  document: { version: 1, blocks: [{ type: 'paragraph', content: [{ type: 'text', text: 'Solar panels.' }] }] },
  target: { kind: 'cursor', position: 3 },
  nearbyText: 'We install solar panels on residential roofs.',
  sectionHeading: 'Solar energy',
};

const visual: VisualDesignIntent = { role: 'inline', intent: 'reinforce' };

function item(over: Partial<MediaItemDto> = {}): MediaItemDto {
  return {
    id: 'm-gen',
    project_id: 'p-1',
    filename: 'Generated image.png',
    mime_type: 'image/png',
    size: 24,
    url: 'https://cdn/p-1/generated.png',
    width: 1024,
    height: 1024,
    alt_text: 'Generated image',
    caption: '',
    source: 'openai_generated',
    source_meta: { provider: 'openai', model: 'dall-e-3' },
    usage_count: 0,
    created_at: 't',
    updated_at: 't',
    ...over,
  };
}

function provider(generate: MediaProvider['generate'], configured = true): MediaProvider {
  return {
    id: 'openai_media',
    name: 'OpenAI images',
    description: 'generate',
    capabilities: ['generate'],
    isConfigured: () => configured,
    generate,
  };
}

function okFetch(bytes: Buffer): typeof fetch {
  return (async () =>
    new Response(new Uint8Array(bytes), {
      status: 200,
      headers: { 'content-type': 'image/png', 'content-length': String(bytes.length) },
    })) as unknown as typeof fetch;
}

async function expectApiError(promise: Promise<unknown>): Promise<{ status: number; code: string }> {
  try {
    await promise;
  } catch (err) {
    return err as { status: number; code: string };
  }
  throw new Error('Expected the generation to throw');
}

describe('imageGenerationModel', () => {
  it('reports the request override or the fixed default', () => {
    expect(imageGenerationModel()).toBe(IMAGE_GENERATION_DEFAULT_MODEL);
    expect(imageGenerationModel('  ')).toBe(IMAGE_GENERATION_DEFAULT_MODEL);
    expect(imageGenerationModel('gpt-image-1')).toBe('gpt-image-1');
  });
});

describe('buildImageGenerationPrompt', () => {
  it('carries the context subject and asks for text-free imagery', () => {
    const prompt = buildImageGenerationPrompt(context, visual);
    expect(prompt).toContain('Solar energy');
    expect(prompt).toContain('No text, no watermark, no logos.');
    expect(prompt.length).toBeLessThanOrEqual(900);
  });

  it('uses a role-aware style', () => {
    expect(buildImageGenerationPrompt(context, { role: 'hero', intent: 'emphasis', placement: 'full_bleed' })).toContain(
      'hero photograph',
    );
    expect(
      buildImageGenerationPrompt(context, { role: 'background', intent: 'atmosphere', placement: 'full_bleed' }),
    ).toContain('background photograph');
  });

  it('leads the prompt with the subject named in the instruction', () => {
    const prompt = buildImageGenerationPrompt(context, visual, 'amsterdam');
    expect(prompt).toContain('for: amsterdam');
  });
});

describe('acquireGeneratedImage', () => {
  it('refuses when generation is not configured', async () => {
    const err = await expectApiError(
      acquireGeneratedImage({
        projectId: 'p-1',
        context,
        visual,
        apiKey: null,
        provider: provider(async () => ({ id: 'x', url: 'https://x/y.png', source: 'openai' }), false),
        persist: vi.fn(),
      }),
    );
    expect(err).toMatchObject({ status: 422, code: 'image_generation_not_configured' });
  });

  it('reports an honest error when the provider rejects the generation', async () => {
    const err = await expectApiError(
      acquireGeneratedImage({
        projectId: 'p-1',
        context,
        visual,
        apiKey: 'sk-test',
        provider: provider(async () => {
          throw new Error('moderation blocked');
        }),
        persist: vi.fn(),
      }),
    );
    expect(err).toMatchObject({ status: 502, code: 'image_generation_failed' });
  });

  it('decodes an inline data URL and persists it with non-secret provenance', async () => {
    const bytes = pngBuffer();
    const persist = vi.fn(async (input: ImportExternalMediaInput) => item({ alt_text: input.alt ?? '' }));
    const candidate = await acquireGeneratedImage({
      projectId: 'p-1',
      context,
      visual,
      apiKey: 'sk-test',
      model: 'dall-e-3',
      provider: provider(async (): Promise<MediaResult> => {
        return {
          id: 'g1',
          url: `data:image/png;base64,${bytes.toString('base64')}`,
          description: 'A solar roof',
          source: 'openai',
        };
      }),
      persist,
    });

    expect(persist).toHaveBeenCalledTimes(1);
    const input = persist.mock.calls[0][0];
    expect(input.source).toBe('openai_generated');
    expect(input.sourceMeta).toEqual({ provider: 'openai', model: 'dall-e-3' });
    expect(input.bytes).toHaveLength(bytes.length);
    expect(candidate).toMatchObject({
      assetId: 'm-gen',
      url: 'https://cdn/p-1/generated.png',
      source: 'openai_generated',
      width: 1024,
      height: 1024,
    });
  });

  it('downloads a provider-hosted URL within the byte budget', async () => {
    const persist = vi.fn(async () => item());
    await acquireGeneratedImage({
      projectId: 'p-1',
      context,
      visual,
      apiKey: 'sk-test',
      provider: provider(async () => ({ id: 'g1', url: 'https://oaidalleapi.blob.core.windows.net/x.png', source: 'openai' })),
      persist,
      fetchFn: okFetch(pngBuffer()),
    });
    expect(persist).toHaveBeenCalledTimes(1);
  });

  it('refuses a non-https generated URL', async () => {
    const err = await expectApiError(
      acquireGeneratedImage({
        projectId: 'p-1',
        context,
        visual,
        apiKey: 'sk-test',
        provider: provider(async () => ({ id: 'g1', url: 'http://insecure.example/x.png', source: 'openai' })),
        persist: vi.fn(),
        fetchFn: okFetch(pngBuffer()),
      }),
    );
    expect(err).toMatchObject({ status: 502, code: 'image_generation_failed' });
  });

  it('refuses an over-large generated download', async () => {
    const fetchFn = (async () =>
      new Response(new Uint8Array(pngBuffer()), {
        status: 200,
        headers: { 'content-length': '999999999' },
      })) as unknown as typeof fetch;
    const err = await expectApiError(
      acquireGeneratedImage({
        projectId: 'p-1',
        context,
        visual,
        apiKey: 'sk-test',
        provider: provider(async () => ({ id: 'g1', url: 'https://oaidalleapi.blob.core.windows.net/x.png', source: 'openai' })),
        persist: vi.fn(),
        fetchFn,
      }),
    );
    expect(err).toMatchObject({ status: 422, code: 'generated_image_too_large' });
  });

  it('reports an honest error when persistence fails', async () => {
    const bytes = pngBuffer();
    const err = await expectApiError(
      acquireGeneratedImage({
        projectId: 'p-1',
        context,
        visual,
        apiKey: 'sk-test',
        provider: provider(async () => ({ id: 'g1', url: `data:image/png;base64,${bytes.toString('base64')}`, source: 'openai' })),
        persist: async () => {
          throw new Error('db down');
        },
      }),
    );
    expect(err).toMatchObject({ status: 502, code: 'asset_persistence_failed' });
  });

  it('bounds a slow generation with a timeout', async () => {
    const err = await expectApiError(
      acquireGeneratedImage({
        projectId: 'p-1',
        context,
        visual,
        apiKey: 'sk-test',
        provider: provider(() => new Promise(() => undefined)),
        persist: vi.fn(),
        timeoutMs: 10,
      }),
    );
    expect(err).toMatchObject({ status: 502, code: 'image_generation_failed' });
  });
});
