export { EditorWorkspace } from './EditorWorkspace';
export type { EditorWorkspaceProps } from './EditorWorkspace';
export { WorkspaceStateProvider, useDocumentScopedState, useWorkspaceScope } from './workspaceState';
export { DocumentHeader, SAVE_LABEL } from './DocumentHeader';
export type { DocumentHeaderProps } from './DocumentHeader';
export { ContextualToolbar } from './ContextualToolbar';
export { IntelligenceRail } from './IntelligenceRail';
export type { IntelligenceRailProps, RailTab } from './IntelligenceRail';
export { PreviewPane } from './PreviewPane';
export type { PreviewViewport } from './previewViewport';
export { DEFAULT_PREVIEW_VIEWPORT, PREVIEW_VIEWPORTS, previewViewportWidth } from './previewViewport';
export { InlineAssistantSlot } from './InlineAssistantSlot';
export { EmbeddedAgentEntry } from './EmbeddedAgentEntry';
export type { EmbeddedAgentEntryProps } from './EmbeddedAgentEntry';
export { EmbeddedAgentInput } from './EmbeddedAgentInput';
export { EmbeddedAgentStatus } from './EmbeddedAgentStatus';
export { useEmbeddedAgent } from './useEmbeddedAgent';
export type { EmbeddedAgentState, EmbeddedAgentOutcome } from './embeddedAgent';
export { CollapsibleSection } from './CollapsibleSection';
